import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
  ForbiddenException,
} from '@nestjs/common';
import * as crypto from 'crypto';
import { DatabaseService } from '../../database/database.service';
import { checkinDevices } from '../../database/schema';
import { eq } from 'drizzle-orm';

@Injectable()
export class DeviceAuthGuard implements CanActivate {
  constructor(private readonly databaseService: DatabaseService) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest();

    const deviceId = request.headers['x-device-id'] as string;
    const timestamp = request.headers['x-device-timestamp'] as string;
    const signature = request.headers['x-device-signature'] as string;

    // Device registration does not require pre-existing headers
    if (request.path.endsWith('/scanner/register')) {
      return true;
    }

    if (!deviceId || !timestamp || !signature) {
      throw new UnauthorizedException('Missing required device authentication headers (X-Device-Id, X-Device-Timestamp, X-Device-Signature)');
    }

    // Prevent replay attacks (5 minute window)
    const requestTime = new Date(timestamp).getTime();
    const now = Date.now();
    if (isNaN(requestTime) || Math.abs(now - requestTime) > 5 * 60 * 1000) {
      throw new UnauthorizedException('Device request timestamp is expired or out of tolerance');
    }

    // Query device from DB
    const device = await this.databaseService.db.query.checkinDevices.findFirst({
      where: eq(checkinDevices.id, deviceId),
    });

    if (!device || device.status !== 'active') {
      throw new ForbiddenException('Scanner device is invalid, unapproved, or has been revoked');
    }

    // Verify cryptographic proof of possession of device private key
    // Reconstruct canonical string: deviceId|timestamp|method|path
    const canonicalStr = `${deviceId}|${timestamp}|${request.method.toUpperCase()}|${request.path}`;

    if (!device.publicKeyPem) {
      throw new UnauthorizedException('Scanner device has no registered public key on file');
    }

    const isValid = this.verifyDeviceSignature(canonicalStr, signature, device.publicKeyPem);
    if (!isValid) {
      throw new UnauthorizedException('Invalid device cryptographic signature: proof of private key possession failed');
    }

    request.device = device;
    return true;
  }

  private verifyDeviceSignature(canonicalStr: string, signatureBase64Url: string, publicKeyPem: string): boolean {
    try {
      const signatureBuf = Buffer.from(signatureBase64Url, 'base64url');
      const dataBuf = Buffer.from(canonicalStr, 'utf8');

      // 1. Try IEEE P1363 encoding (raw 64-byte r || s as generated by mobile devices)
      if (signatureBuf.length === 64) {
        try {
          const valid = crypto.verify(
            'SHA256',
            dataBuf,
            {
              key: publicKeyPem,
              dsaEncoding: 'ieee-p1363',
            },
            signatureBuf,
          );
          if (valid) return true;
        } catch {
          // Fall through to standard DER check
        }
      }

      // 2. Try standard ASN.1 DER encoding
      return crypto.verify('SHA256', dataBuf, publicKeyPem, signatureBuf);
    } catch {
      return false;
    }
  }
}
