// =============================================================================
// Drizzle ORM Schema — synchronized with database/migrations/0001_initial_schema.sql
// DO NOT edit this file independently of the SQL migration.
// If you change the database schema, update the SQL migration first,
// then update this file to match.
// =============================================================================
import { sql } from 'drizzle-orm';
import {
  pgTable,
  uuid,
  text,
  integer,
  bigint,
  boolean,
  timestamp,
  numeric,
  char,
  json,
  unique,
  primaryKey,
  index,
  pgEnum,
} from 'drizzle-orm/pg-core';
import { citext } from './citext';

// ---------------------------------------------------------------------------
// ENUMs
// ---------------------------------------------------------------------------
export const userStatusEnum = pgEnum('user_status', ['active', 'suspended', 'deleted']);
export const organizationTypeEnum = pgEnum('organization_type', ['organizer', 'venue', 'promoter']);
export const organizationStatusEnum = pgEnum('organization_status', ['pending', 'active', 'suspended', 'rejected']);
export const eventStatusEnum = pgEnum('event_status', [
  'draft', 'submitted', 'under_review', 'approved', 'published',
  'live', 'completed', 'rejected', 'suspended', 'cancelled',
]);
export const ticketStatusEnum = pgEnum('ticket_status', [
  'issued', 'checked_in', 'refunded', 'void', 'cancelled', 'expired',
]);
export const orderStatusEnum = pgEnum('order_status', [
  'created', 'payment_pending', 'paid', 'tickets_issued', 'completed',
  'payment_failed', 'cancelled', 'expired', 'refund_pending', 'partially_refunded', 'refunded',
]);
export const paymentStatusEnum = pgEnum('payment_status', [
  'pending', 'authorized', 'paid', 'failed', 'cancelled', 'refunded', 'partially_refunded',
]);
export const refundStatusEnum = pgEnum('refund_status', [
  'requested', 'pending', 'processing', 'completed', 'failed', 'cancelled',
]);
export const settlementStatusEnum = pgEnum('settlement_status', [
  'draft', 'pending_review', 'approved', 'processing', 'paid', 'failed', 'cancelled',
]);
export const checkinResultEnum = pgEnum('checkin_result', [
  'success', 'invalid', 'already_used', 'wrong_event',
  'refunded', 'cancelled', 'expired', 'access_denied', 'offline_pending',
]);
export const notificationStatusEnum = pgEnum('notification_status', [
  'queued', 'sent', 'delivered', 'failed', 'read',
]);

// ---------------------------------------------------------------------------
// USERS
// ---------------------------------------------------------------------------
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  // supabaseAuthId maps auth.users.id → public.users.id
  // NOT NULL and UNIQUE — enforced from day one (no production users exist).
  // All relational FKs in other tables reference users.id (app UUID),
  // NOT supabaseAuthId, so this column is never a FK target itself.
  supabaseAuthId: uuid('supabase_auth_id').notNull().unique(),
  email: citext('email').unique(),
  phone: text('phone'),
  name: text('name').notNull(),
  avatarUrl: text('avatar_url'),
  status: userStatusEnum('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ROLES & PERMISSIONS
// ---------------------------------------------------------------------------
export const roles = pgTable('roles', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationType: organizationTypeEnum('organization_type'),
  name: text('name').notNull(),
}, (t) => ({ unqRoleName: unique().on(t.organizationType, t.name) }));

export const permissions = pgTable('permissions', {
  id: uuid('id').primaryKey().defaultRandom(),
  key: text('key').unique().notNull(),
  description: text('description'),
});

export const rolePermissions = pgTable('role_permissions', {
  roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }),
  permissionId: uuid('permission_id').notNull().references(() => permissions.id, { onDelete: 'cascade' }),
}, (t) => ({ pk: primaryKey({ columns: [t.roleId, t.permissionId] }) }));

// ---------------------------------------------------------------------------
// ORGANIZATIONS
// ---------------------------------------------------------------------------
export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: organizationTypeEnum('type').notNull(),
  name: text('name').notNull(),
  slug: citext('slug').unique().notNull(),
  description: text('description'),
  logoUrl: text('logo_url'),
  status: organizationStatusEnum('status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const organizationMembers = pgTable('organization_members', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'restrict' }),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ unqMember: unique().on(t.organizationId, t.userId) }));

export const organizationInvitations = pgTable('organization_invitations', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  invitedEmail: citext('invited_email').notNull(),
  roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'restrict' }),
  invitedBy: uuid('invited_by').notNull().references(() => users.id, { onDelete: 'restrict' }),
  // token_hash = sha256(raw_token). Raw token returned once in response, never stored plaintext.
  tokenHash: text('token_hash').notNull().unique(),
  // pending | accepted | expired | revoked
  status: text('status').notNull().default('pending'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  acceptedBy: uuid('accepted_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// VENUES
// ---------------------------------------------------------------------------
export const venues = pgTable('venues', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'restrict' }),
  name: text('name').notNull(),
  slug: citext('slug').unique().notNull(),
  description: text('description'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  country: text('country').default('IN'),
  latitude: numeric('latitude', { precision: 9, scale: 6 }),
  longitude: numeric('longitude', { precision: 9, scale: 6 }),
  capacity: integer('capacity'),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const venueMedia = pgTable('venue_media', {
  id: uuid('id').primaryKey().defaultRandom(),
  venueId: uuid('venue_id').notNull().references(() => venues.id, { onDelete: 'cascade' }),
  url: text('url').notNull(),
  type: text('type').notNull().default('image'),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const venueAvailability = pgTable('venue_availability', {
  id: uuid('id').primaryKey().defaultRandom(),
  venueId: uuid('venue_id').notNull().references(() => venues.id, { onDelete: 'cascade' }),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  status: text('status').notNull().default('available'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// EVENTS
// ---------------------------------------------------------------------------
export const eventCategories = pgTable('event_categories', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: citext('slug').unique().notNull(),
  status: text('status').notNull().default('active'),
});

export const events = pgTable('events', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizerOrganizationId: uuid('organizer_organization_id').notNull().references(() => organizations.id, { onDelete: 'restrict' }),
  venueId: uuid('venue_id').references(() => venues.id, { onDelete: 'restrict' }),
  categoryId: uuid('category_id').references(() => eventCategories.id, { onDelete: 'set null' }),
  title: text('title').notNull(),
  slug: citext('slug').unique().notNull(),
  description: text('description'),
  status: eventStatusEnum('status').notNull().default('draft'),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  timezone: text('timezone').notNull().default('Asia/Kolkata'),
  capacity: integer('capacity'),
  ageRestriction: text('age_restriction'),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const eventMedia = pgTable('event_media', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  url: text('url').notNull(),
  type: text('type').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const eventLineups = pgTable('event_lineups', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  role: text('role'),
  sortOrder: integer('sort_order').notNull().default(0),
});

// ---------------------------------------------------------------------------
// TICKETS
// ---------------------------------------------------------------------------
export const ticketTypes = pgTable('ticket_types', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  description: text('description'),
  priceMinor: bigint('price_minor', { mode: 'number' }).notNull(),
  currency: char('currency', { length: 3 }).notNull().default('INR'),
  quantity: integer('quantity').notNull(),
  soldQuantity: integer('sold_quantity').notNull().default(0),
  reservedQuantity: integer('reserved_quantity').notNull().default(0),
  minPerOrder: integer('min_per_order').notNull().default(1),
  maxPerOrder: integer('max_per_order').notNull().default(10),
  saleStartsAt: timestamp('sale_starts_at', { withTimezone: true }),
  saleEndsAt: timestamp('sale_ends_at', { withTimezone: true }),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const orders = pgTable('orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'restrict' }),
  status: orderStatusEnum('status').notNull().default('created'),
  subtotalMinor: bigint('subtotal_minor', { mode: 'number' }).notNull().default(0),
  feesMinor: bigint('fees_minor', { mode: 'number' }).notNull().default(0),
  taxMinor: bigint('tax_minor', { mode: 'number' }).notNull().default(0),
  discountMinor: bigint('discount_minor', { mode: 'number' }).notNull().default(0),
  totalMinor: bigint('total_minor', { mode: 'number' }).notNull().default(0),
  currency: char('currency', { length: 3 }).notNull().default('INR'),
  idempotencyKey: text('idempotency_key').unique(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const orderItems = pgTable('order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  ticketTypeId: uuid('ticket_type_id').notNull().references(() => ticketTypes.id, { onDelete: 'restrict' }),
  quantity: integer('quantity').notNull(),
  unitPriceMinor: bigint('unit_price_minor', { mode: 'number' }).notNull(),
  totalMinor: bigint('total_minor', { mode: 'number' }).notNull(),
});

export const inventoryReservations = pgTable('inventory_reservations', {
  id: uuid('id').primaryKey().defaultRandom(),
  ticketTypeId: uuid('ticket_type_id').notNull().references(() => ticketTypes.id, { onDelete: 'restrict' }),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'restrict' }),
  quantity: integer('quantity').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const idempotencyRecords = pgTable('idempotency_records', {
  id: uuid('id').primaryKey().defaultRandom(),
  idempotencyKey: text('idempotency_key').notNull(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  requestPath: text('request_path').notNull(),
  requestHash: text('request_hash').notNull(),
  responseStatus: integer('response_status').notNull(),
  responseBody: json('response_body').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  ukIdempotencyKeyUser: unique('uk_idempotency_key_user').on(t.idempotencyKey, t.userId),
}));

export const tickets = pgTable('tickets', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  orderItemId: uuid('order_item_id').notNull().references(() => orderItems.id, { onDelete: 'restrict' }),
  ticketTypeId: uuid('ticket_type_id').notNull().references(() => ticketTypes.id, { onDelete: 'restrict' }),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'restrict' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  ticketNumber: text('ticket_number').unique().notNull(),
  status: ticketStatusEnum('status').notNull().default('issued'),
  qrTokenHash: text('qr_token_hash').unique().notNull(),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
  checkedInAt: timestamp('checked_in_at', { withTimezone: true }),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// PAYMENTS
// ---------------------------------------------------------------------------
export const paymentTransactions = pgTable('payment_transactions', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  provider: text('provider').notNull(),
  providerOrderId: text('provider_order_id'),
  providerPaymentId: text('provider_payment_id').unique(),
  amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
  currency: char('currency', { length: 3 }).notNull().default('INR'),
  status: paymentStatusEnum('status').notNull().default('pending'),
  providerPayloadReference: text('provider_payload_reference'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const paymentEvents = pgTable('payment_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  paymentTransactionId: uuid('payment_transaction_id').references(() => paymentTransactions.id, { onDelete: 'set null' }),
  providerEventId: text('provider_event_id').unique().notNull(),
  eventType: text('event_type').notNull(),
  payloadReference: text('payload_reference'),
  receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  processedAt: timestamp('processed_at', { withTimezone: true }),
  status: text('status').notNull().default('received'),
});

// ---------------------------------------------------------------------------
// REFUNDS
// ---------------------------------------------------------------------------
export const refunds = pgTable('refunds', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  paymentTransactionId: uuid('payment_transaction_id').references(() => paymentTransactions.id, { onDelete: 'restrict' }),
  amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
  reason: text('reason'),
  status: refundStatusEnum('status').notNull().default('requested'),
  providerRefundId: text('provider_refund_id').unique(),
  requestedBy: uuid('requested_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// CHECKINS
// ---------------------------------------------------------------------------
export const checkinDevices = pgTable('checkin_devices', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'restrict' }),
  deviceIdentifier: text('device_identifier').unique().notNull(),
  status: text('status').notNull().default('active'),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
});

export const checkinGates = pgTable('checkin_gates', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  status: text('status').notNull().default('active'),
}, (t) => ({ unqEventTierName: unique().on(t.eventId, t.name) }));

export const checkins = pgTable('checkins', {
  id: uuid('id').primaryKey().defaultRandom(),
  ticketId: uuid('ticket_id').notNull().references(() => tickets.id, { onDelete: 'restrict' }),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'restrict' }),
  gateId: uuid('gate_id').references(() => checkinGates.id, { onDelete: 'set null' }),
  deviceId: uuid('device_id').references(() => checkinDevices.id, { onDelete: 'set null' }),
  staffUserId: uuid('staff_user_id').references(() => users.id, { onDelete: 'set null' }),
  result: checkinResultEnum('result').notNull(),
  scannedAt: timestamp('scanned_at', { withTimezone: true }).notNull(),
  serverRecordedAt: timestamp('server_recorded_at', { withTimezone: true }).notNull().defaultNow(),
  syncId: uuid('sync_id').unique().notNull(),
});

// ---------------------------------------------------------------------------
// PROMOTERS
// ---------------------------------------------------------------------------
export const promoterProfiles = pgTable('promoter_profiles', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').unique().notNull().references(() => organizations.id, { onDelete: 'restrict' }),
  status: text('status').notNull().default('active'),
});

export const promoterCampaigns = pgTable('promoter_campaigns', {
  id: uuid('id').primaryKey().defaultRandom(),
  promoterId: uuid('promoter_id').notNull().references(() => promoterProfiles.id, { onDelete: 'restrict' }),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'restrict' }),
  code: text('code').notNull(),
  commissionType: text('commission_type').notNull(),
  commissionValue: numeric('commission_value', { precision: 12, scale: 4 }).notNull(),
  status: text('status').notNull().default('active'),
}, (t) => ({ unqPromoterCode: unique().on(t.eventId, t.code) }));

export const referralClicks = pgTable('referral_clicks', {
  id: uuid('id').primaryKey().defaultRandom(),
  campaignId: uuid('campaign_id').notNull().references(() => promoterCampaigns.id, { onDelete: 'cascade' }),
  sessionReference: text('session_reference'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const referralAttributions = pgTable('referral_attributions', {
  id: uuid('id').primaryKey().defaultRandom(),
  campaignId: uuid('campaign_id').notNull().references(() => promoterCampaigns.id, { onDelete: 'restrict' }),
  orderId: uuid('order_id').unique().notNull().references(() => orders.id, { onDelete: 'restrict' }),
  attributedAt: timestamp('attributed_at', { withTimezone: true }).notNull().defaultNow(),
});

export const commissionEntries = pgTable('commission_entries', {
  id: uuid('id').primaryKey().defaultRandom(),
  campaignId: uuid('campaign_id').notNull().references(() => promoterCampaigns.id, { onDelete: 'restrict' }),
  orderId: uuid('order_id').notNull().references(() => orders.id, { onDelete: 'restrict' }),
  commissionType: text('commission_type'),
  commissionValue: numeric('commission_value', { precision: 12, scale: 4 }),
  calculationBaseMinor: bigint('calculation_base_minor', { mode: 'number' }),
  ticketQuantity: integer('ticket_quantity').default(1),
  amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
  currency: char('currency', { length: 3 }).notNull().default('INR'),
  status: text('status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// FINANCE & SETTLEMENTS (PHASE 10)
// ---------------------------------------------------------------------------
export const financialTransactions = pgTable('financial_transactions', {
  id: uuid('id').primaryKey().defaultRandom(),
  transactionNumber: text('transaction_number').unique().notNull(),
  transactionType: text('transaction_type').notNull(),
  status: text('status').notNull().default('posted'),
  currency: text('currency').notNull().default('INR'),
  referenceType: text('reference_type').notNull(),
  referenceId: uuid('reference_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  postedAt: timestamp('posted_at', { withTimezone: true }).notNull().defaultNow(),
});

export const ledgerEntries = pgTable('ledger_entries', {
  id: uuid('id').primaryKey().defaultRandom(),
  transactionId: uuid('transaction_id').notNull().references(() => financialTransactions.id, { onDelete: 'cascade' }),
  account: text('account').notNull(),
  debitMinor: bigint('debit_minor', { mode: 'number' }).notNull().default(sql`0`),
  creditMinor: bigint('credit_minor', { mode: 'number' }).notNull().default(sql`0`),
  currency: text('currency').notNull().default('INR'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const settlements = pgTable('settlements', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'restrict' }),
  eventId: uuid('event_id').references(() => events.id, { onDelete: 'set null' }),
  grossSalesMinor: bigint('gross_sales_minor', { mode: 'number' }).notNull().default(sql`0`),
  refundsMinor: bigint('refunds_minor', { mode: 'number' }).notNull().default(sql`0`),
  platformCommissionMinor: bigint('platform_commission_minor', { mode: 'number' }).notNull().default(sql`0`),
  promoterCommissionMinor: bigint('promoter_commission_minor', { mode: 'number' }).notNull().default(sql`0`),
  taxMinor: bigint('tax_minor', { mode: 'number' }).notNull().default(sql`0`),
  netSettlementMinor: bigint('net_settlement_minor', { mode: 'number' }).notNull().default(sql`0`),
  status: settlementStatusEnum('status').notNull().default('draft'),
  periodStart: timestamp('period_start', { withTimezone: true }).notNull(),
  periodEnd: timestamp('period_end', { withTimezone: true }).notNull(),
  idempotencyKey: text('idempotency_key').unique().notNull(),
  preparedBy: uuid('prepared_by').notNull().references(() => users.id, { onDelete: 'restrict' }),
  preparedAt: timestamp('prepared_at', { withTimezone: true }).notNull().defaultNow(),
  approvedBy: uuid('approved_by').references(() => users.id, { onDelete: 'set null' }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  rejectionReason: text('rejection_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ unqSettlementScope: unique().on(t.organizationId, t.eventId, t.periodStart, t.periodEnd) }));

export const settlementItems = pgTable('settlement_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  settlementId: uuid('settlement_id').notNull().references(() => settlements.id, { onDelete: 'restrict' }),
  referenceType: text('reference_type').notNull(),
  referenceId: uuid('reference_id').notNull(),
  amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
});

// ---------------------------------------------------------------------------
// NOTIFICATIONS
// ---------------------------------------------------------------------------
export const notificationPreferences = pgTable('notification_preferences', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  channel: text('channel').notNull(),
  category: text('category').notNull(),
  enabled: boolean('enabled').notNull().default(true),
}, (t) => ({ unqUserChannelCategory: unique().on(t.userId, t.channel, t.category) }));

export const notifications = pgTable('notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  type: text('type').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  dataReference: text('data_reference'),
  status: notificationStatusEnum('status').notNull().default('queued'),
  sentAt: timestamp('sent_at', { withTimezone: true }),
  readAt: timestamp('read_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const deviceTokens = pgTable('device_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  deviceId: text('device_id').notNull().default('device_unknown'),
  token: text('token').notNull(),
  platform: text('platform').notNull(),
  active: boolean('active').notNull().default(true),
  lastActiveAt: timestamp('last_active_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ unqDevicePlatformToken: unique().on(t.platform, t.token) }));

// ---------------------------------------------------------------------------
// SUPPORT
// ---------------------------------------------------------------------------
export const supportTickets = pgTable('support_tickets', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  category: text('category').notNull(),
  priority: text('priority').notNull().default('normal'),
  status: text('status').notNull().default('open'),
  subject: text('subject').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const supportMessages = pgTable('support_messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  ticketId: uuid('ticket_id').notNull().references(() => supportTickets.id, { onDelete: 'cascade' }),
  senderUserId: uuid('sender_user_id').references(() => users.id, { onDelete: 'set null' }),
  body: text('body').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// MODERATION & AUDIT
// ---------------------------------------------------------------------------
export const moderationCases = pgTable('moderation_cases', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  reason: text('reason').notNull(),
  severity: text('severity').notNull(),
  status: text('status').notNull().default('open'),
  assignedTo: uuid('assigned_to').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
});

export const riskFlags = pgTable('risk_flags', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id').notNull(),
  rule: text('rule').notNull(),
  severity: text('severity').notNull(),
  status: text('status').notNull().default('open'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').primaryKey().defaultRandom(),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  action: text('action').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: uuid('entity_id'),
  metadata: text('metadata').notNull().default('{}'), // stored as JSON string
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// RECONCILIATION (PHASE 10)
// ---------------------------------------------------------------------------

export const reconciliationRuns = pgTable('reconciliation_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  reconciliationDate: timestamp('reconciliation_date', { withTimezone: true }).notNull().defaultNow(),
  totalOrdersCount: integer('total_orders_count').notNull().default(0),
  totalMatchedCount: integer('total_matched_count').notNull().default(0),
  totalMismatchedCount: integer('total_mismatched_count').notNull().default(0),
  status: text('status').notNull().default('clean'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const reconciliationExceptions = pgTable('reconciliation_exceptions', {
  id: uuid('id').primaryKey().defaultRandom(),
  reconciliationRunId: uuid('reconciliation_run_id').notNull().references(() => reconciliationRuns.id, { onDelete: 'cascade' }),
  internalReference: text('internal_reference').notNull(),
  providerReference: text('provider_reference'),
  expectedAmountMinor: bigint('expected_amount_minor', { mode: 'number' }).notNull().default(sql`0`),
  actualAmountMinor: bigint('actual_amount_minor', { mode: 'number' }).notNull().default(sql`0`),
  currency: text('currency').notNull().default('INR'),
  differenceMinor: bigint('difference_minor', { mode: 'number' }).notNull().default(sql`0`),
  mismatchType: text('mismatch_type').notNull(),
  status: text('status').notNull().default('open'),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  resolvedBy: uuid('resolved_by').references(() => users.id, { onDelete: 'set null' }),
});

// ---------------------------------------------------------------------------
// NOTIFICATIONS & CMS (PHASE 11)
// ---------------------------------------------------------------------------
export const notificationOutbox = pgTable('notification_outbox', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: text('event_id'),
  notificationType: text('notification_type').notNull(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  payloadJson: text('payload_json').notNull(),
  status: text('status').notNull().default('pending'),
  idempotencyKey: text('idempotency_key').unique().notNull(),
  retryCount: integer('retry_count').notNull().default(0),
  lockedAt: timestamp('locked_at', { withTimezone: true }),
  lockedBy: text('locked_by'),
  nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }),
  processedAt: timestamp('processed_at', { withTimezone: true }),
  lastError: text('last_error'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});


export const notificationTemplates = pgTable('notification_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  notificationType: text('notification_type').notNull(),
  locale: text('locale').notNull().default('en'),
  channel: text('channel').notNull(),
  version: integer('version').notNull().default(1),
  subject: text('subject').notNull(),
  bodyTemplate: text('body_template').notNull(),
  variablesJson: text('variables_json').notNull().default('[]'),
}, (t) => ({ unqTemplateVersion: unique().on(t.notificationType, t.locale, t.channel, t.version) }));

export const notificationLogs = pgTable('notification_logs', {
  id: uuid('id').primaryKey().defaultRandom(),
  outboxId: uuid('outbox_id').references(() => notificationOutbox.id, { onDelete: 'set null' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  notificationType: text('notification_type').notNull(),
  channel: text('channel').notNull(),
  recipient: text('recipient').notNull(),
  subject: text('subject').notNull(),
  status: text('status').notNull().default('queued'),
  providerMessageId: text('provider_message_id'),
  failureReason: text('failure_reason'),
  retryCount: integer('retry_count').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const notificationDeliveryAttempts = pgTable('notification_delivery_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  logId: uuid('log_id').notNull().references(() => notificationLogs.id, { onDelete: 'cascade' }),
  attemptNumber: integer('attempt_number').notNull(),
  provider: text('provider').notNull(),
  providerMessageId: text('provider_message_id'),
  status: text('status').notNull(),
  failureReason: text('failure_reason'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

export const inAppNotifications = pgTable('in_app_notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  body: text('body').notNull(),
  metadata: text('metadata').notNull().default('{}'),
  read: boolean('read').notNull().default(false),
  readAt: timestamp('read_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const cmsBanners = pgTable('cms_banners', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  imageUrl: text('image_url').notNull(),
  targetUrl: text('target_url').notNull(),
  displayOrder: integer('display_order').notNull().default(0),
  status: text('status').notNull().default('draft'),
  startAt: timestamp('start_at', { withTimezone: true }),
  endAt: timestamp('end_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const cmsFeaturedEvents = pgTable('cms_featured_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  displayOrder: integer('display_order').notNull().default(0),
  badgeText: text('badge_text'),
  status: text('status').notNull().default('published'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const cmsCollections = pgTable('cms_collections', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').unique().notNull(),
  description: text('description'),
  coverImageUrl: text('cover_image_url'),
  status: text('status').notNull().default('draft'),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const cmsCollectionEvents = pgTable('cms_collection_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  collectionId: uuid('collection_id').notNull().references(() => cmsCollections.id, { onDelete: 'cascade' }),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  displayOrder: integer('display_order').notNull().default(0),
}, (t) => ({ unqCollectionEvent: unique().on(t.collectionId, t.eventId) }));

export const cmsEditorialBlocks = pgTable('cms_editorial_blocks', {
  id: uuid('id').primaryKey().defaultRandom(),
  blockType: text('block_type').notNull(),
  headline: text('headline').notNull(),
  bodyMarkdown: text('body_markdown').notNull(),
  mediaUrl: text('media_url'),
  displayOrder: integer('display_order').notNull().default(0),
  status: text('status').notNull().default('draft'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ANALYTICS & FUNNELS (PHASE 12)
// ---------------------------------------------------------------------------
export const analyticsEvents = pgTable('analytics_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  clientEventId: text('client_event_id').unique(),
  eventName: text('event_name').notNull(),
  eventId: uuid('event_id').references(() => events.id, { onDelete: 'set null' }),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  sessionId: text('session_id'),
  platform: text('platform').notNull().default('web'),
  appVersion: text('app_version'),
  propertiesJson: text('properties_json').notNull().default('{}'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
});

export const analyticsAggregatesDaily = pgTable('analytics_aggregates_daily', {
  id: uuid('id').primaryKey().defaultRandom(),
  aggregateDate: timestamp('aggregate_date', { withTimezone: true }).notNull(),
  metricName: text('metric_name').notNull(),
  dimensionType: text('dimension_type'),
  dimensionId: text('dimension_id'),
  metricValue: bigint('metric_value', { mode: 'number' }).notNull().default(sql`0`),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ unqAggregateDimension: unique().on(t.aggregateDate, t.metricName, t.dimensionType, t.dimensionId) }));

// Indexes are defined inline within table definitions using the third argument.
// See table definitions above for all index declarations.
// The following are named references for documentation purposes only.
export const INDEX_EVENTS_STATUS_START = 'idx_events_status_start';
export const INDEX_EVENTS_CATEGORY = 'idx_events_category';
export const INDEX_EVENTS_ORGANIZER = 'idx_events_organizer';
export const INDEX_TICKET_TYPES_EVENT = 'idx_ticket_types_event';
export const INDEX_ORDERS_USER = 'idx_orders_user';
export const INDEX_ORDERS_EVENT = 'idx_orders_event';
export const INDEX_TICKETS_EVENT = 'idx_tickets_event';
export const INDEX_TICKETS_ORDER = 'idx_tickets_order';
export const INDEX_CHECKINS_EVENT = 'idx_checkins_event_time';
export const INDEX_NOTIFICATIONS_USER_STATUS = 'idx_notifications_user_status';
export const INDEX_USERS_EMAIL_STATUS = 'idx_users_email_status';
export const INDEX_ORDERS_USER_STATUS = 'idx_orders_user_status';
export const INDEX_TICKETS_QR_STATUS = 'idx_tickets_qr_status';
export const INDEX_CHECKINS_EVENT_SCANNED = 'idx_checkins_event_scanned';
export const INDEX_ANALYTICS_EVENTS_NAME_OCCURRED = 'idx_analytics_events_name_occurred';
export const INDEX_NOTIFICATION_OUTBOX_STATUS_LOCKED = 'idx_notification_outbox_status_locked';
