// =============================================================================
// Scanner Mobile — Cryptographic Service Unit & Security Test Suite
// FIX-004: Verifies PointyCastle ECDSA P-256 / SHA-256 verification against
// cross-language test vectors generated by Node.js crypto module.
// =============================================================================

import 'package:flutter_test/flutter_test.dart';
import 'package:scanner_mobile/core/crypto_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late CryptoService cryptoService;

  // ---------------------------------------------------------------------------
  // Deterministic Cross-Language Test Vectors (Generated with Node.js crypto)
  // Curve: prime256v1 (NIST P-256), Hash: SHA-256, Signature: DER / Base64URL
  // ---------------------------------------------------------------------------
  const testServerPublicKeyPem = '''-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwdFEzIXFQIbO17aHS5t2j8T4S7zl
e78rpO8zNj2IF4eIa/LVKqfiidE6LXL0g4+CVZmK+8cv5cag05TRAE4BEQ==
-----END PUBLIC KEY-----''';

  const testOtherPublicKeyPem = '''-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9e2Nk2N4i3Etl9Imkh+oYYiIcY8P
8X7QZ/5cZvZE74Gb0JhoJFeCyP5rSv97pQ1wPM9z4t+gEOJX7RhArw1o1A==
-----END PUBLIC KEY-----''';

  // Valid ticket payload and its Node-generated signature
  const validTicketId = 'tkt-12345';
  const validEventId = 'evt-99999';
  const validTicketTypeId = 'tt-vip';
  const validIssuedAt = '2026-08-19T10:00:00.000Z';
  const validExpiresAt = 'none';
  const validKeyVersion = 'v1-2026';
  const validCanonicalPayload = 'v1|$validTicketId|$validEventId|$validTicketTypeId|$validIssuedAt|$validExpiresAt|$validKeyVersion';
  const validSignature = 'MEQCIDFWVrWV5waIJTWA9h3R6sK2FtSfCfON_9dCy9cVYEXyAiBFfmBxNEe9sL6kOX-HzI396dJP-Aotcjp0COS0bxhTeA';

  setUp(() {
    cryptoService = CryptoService();
  });

  group('FIX-004: Tier 2 Offline Ticket ECDSA P-256 Cryptographic Verification', () {
    test('Cross-Language Verification: Valid Node.js signature verifies successfully', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: validCanonicalPayload,
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isTrue, reason: 'PointyCastle should verify valid Node.js P-256 signature');
    });

    test('Tamper Resistance: Tampered ticketId is cryptographically rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: 'tkt-TAMPERED-999',
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: 'v1|tkt-TAMPERED-999|$validEventId|$validTicketTypeId|$validIssuedAt|$validExpiresAt|$validKeyVersion',
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Tampered ticketId must fail cryptographic verification');
    });

    test('Tamper Resistance: Tampered eventId is rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: 'evt-HACKED-EVENT',
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: 'v1|$validTicketId|evt-HACKED-EVENT|$validTicketTypeId|$validIssuedAt|$validExpiresAt|$validKeyVersion',
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: 'evt-HACKED-EVENT',
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Tampered eventId must fail signature verification');
    });

    test('Tamper Resistance: Wrong event scope is rejected before crypto check', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: validCanonicalPayload,
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: 'evt-OTHER-DIFFERENT-EVENT',
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Scope check must reject ticket for different event');
    });

    test('Tamper Resistance: Tampered signature bytes fail verification', () {
      // Alter one character of the signature
      final badSignature = validSignature.replaceFirst('M', 'N');
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: validCanonicalPayload,
        signature: badSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Altered signature must fail verification');
    });

    test('Key Verification: Signature fails against wrong public key', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: validCanonicalPayload,
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testOtherPublicKeyPem, // Different public key
      );

      expect(isValid, isFalse, reason: 'Verification with wrong public key must fail');
    });

    test('Tamper Resistance: Tampered ticketTypeId is cryptographically rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: 'tt-TAMPERED-VIP',
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: 'v1|$validTicketId|$validEventId|tt-TAMPERED-VIP|$validIssuedAt|$validExpiresAt|$validKeyVersion',
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Tampered ticketTypeId must fail signature verification');
    });

    test('Tamper Resistance: Tampered issuedAt is cryptographically rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: '2026-08-19T12:00:00.000Z',
        expiresAt: null,
        keyVersion: validKeyVersion,
        canonicalPayload: 'v1|$validTicketId|$validEventId|$validTicketTypeId|2026-08-19T12:00:00.000Z|$validExpiresAt|$validKeyVersion',
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Tampered issuedAt timestamp must fail signature verification');
    });

    test('Tamper Resistance: Tampered keyVersion is cryptographically rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: null,
        keyVersion: 'v2-2027',
        canonicalPayload: 'v1|$validTicketId|$validEventId|$validTicketTypeId|$validIssuedAt|$validExpiresAt|v2-2027',
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Tampered keyVersion must fail signature verification');
    });

    test('Expiry Check: Expired ticket credential is rejected', () {
      final credential = ParsedTicketCredential(
        version: 'v1',
        ticketId: validTicketId,
        eventId: validEventId,
        ticketTypeId: validTicketTypeId,
        issuedAt: validIssuedAt,
        expiresAt: '2020-01-01T00:00:00.000Z', // Expired
        keyVersion: validKeyVersion,
        canonicalPayload: validCanonicalPayload,
        signature: validSignature,
      );

      final isValid = cryptoService.verifyTicketOffline(
        credential: credential,
        authorizedEventId: validEventId,
        serverTicketPublicKeyPem: testServerPublicKeyPem,
      );

      expect(isValid, isFalse, reason: 'Expired ticket must be rejected');
    });
  });
}
